"""ability to name the lists

Revision ID: 1030f3352e26
Revises: 4500afbd0eb0
Create Date: 2017-10-14 00:39:15.702614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1030f3352e26'
down_revision = '4500afbd0eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_list', sa.Column('name', sa.String(length=64)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_list', 'name')
    # ### end Alembic commands ###
